name: dlnlp-final-uceezl8
channels:
  - defaults
dependencies:
  - python=3.9
  - black                               # formatter
  - scikit-learn
  - pandas                              # load dataframe
  - ipython                             # debugging
  - pillow                              # read images
  - matplotlib                          # draw figures
  - numpy
  - pip
  - pip:
    - -r requirements.txt
